"""
Django settings for Portolio project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

### ============================================================================================ #
###  IMPORTS
### ============================================================================================ #
import os
from pathlib import Path

from dotenv import load_dotenv



### ============================================================================================ #
### GLOBAL PARAMETERS
### ============================================================================================ #
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# IF WE CREATE THE SETTINGS STRUCTURE LIKE THIS, WE NEED TO ADD ".parent" BELOW, AS THE PATH FROM
# THE SETTINGS FILE IS ONE FILE PATH DEEPER THAN THE NORMAL PATH
BASE_DIR = Path( __file__ ).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get( "DJANGO_SECRET_KEY" )

### ============================================================================================ #
### DEBUG MODE
### ============================================================================================ #
DJANGO_RUN_MODES = {
      'DEVELOPMENT': True,
      'STAGING':     True,
      'PRODUCTION':  False
}

DJANGO_RUN_MODE = os.environ.get( "DJANGO_RUN_MODE" )
match DJANGO_RUN_MODE:
      case 'DEVELOPMENT':
            DEBUG = DJANGO_RUN_MODES[ DJANGO_RUN_MODE ]
            os.environ['DJANGO_SETTINGS_MODULE'] = 'Portolio.settings.development_settings'
      
      case 'STAGING':
            DEBUG = DJANGO_RUN_MODES[ DJANGO_RUN_MODE ]
            os.environ[ 'DJANGO_SETTINGS_MODULE' ] = 'Portolio.settings.staging_settings'
            
      case 'PRODUCTION':
            DEBUG = DJANGO_RUN_MODES[ DJANGO_RUN_MODE ]
            os.environ[ 'DJANGO_SETTINGS_MODULE' ] = 'Portolio.settings.production_settings'

      case _:
            print( "======= !!!!DJANGO_RUN_MODE_ERROR!!!! ========" )




### ============================================================================================ #
### INSTALLED APPS
### ============================================================================================ #
INSTALLED_APPS = [
      'django.contrib.admin',
      'django.contrib.auth',
      'django.contrib.contenttypes',
      'django.contrib.sessions',
      'django.contrib.messages',
      'django.contrib.staticfiles',
      
      ### ==================
      ### DJANGO EXTENSIONS
      'django.contrib.sitemaps',  # SEO
      'django_extensions',  # MODEL EXTENSIONS - https://django-extensions.readthedocs.io
      
      ### ==================
      ### 3-RD PARTY PACKAGES
      'admin_honeypot',  # ADMIN HONEYPOT
      'cloudinary',  # CLOUDINARY
      'django_otp',  # OTP - One Time Password
      'django_otp.plugins.otp_totp',  # OTP - One Time Password
      # 'django_otp.plugins.otp_hotp',  # OTP - One Time Password ==> NOT NEEDED
      # 'django_otp.plugins.otp_static',  # OTP - One Time Password ==> NOT NEEDED
      
      ### ==================
      ### APPS
      'users.apps.UsersConfig',  # Users APP
      'features.apps.FeaturesConfig',  # Development Features APP
]

### ============================================================================================ #
### MIDDLEWEARE
### ============================================================================================ #
MIDDLEWARE = [
      'django.middleware.security.SecurityMiddleware',
      'django.contrib.sessions.middleware.SessionMiddleware',
      'django.middleware.common.CommonMiddleware',
      'django.middleware.csrf.CsrfViewMiddleware',
      'django.contrib.auth.middleware.AuthenticationMiddleware',
      
      ### ==================
      ### DJANGO 3RD-PARTY MIDDLEWARE
      'django_otp.middleware.OTPMiddleware',  # OTP Middleware: must be below auth-Middleware -> https://django-otp-official.readthedocs.io/en/stable/overview.html
      
      'django.contrib.messages.middleware.MessageMiddleware',
      'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Portolio.urls'
# AUTH_USER_MODEL = 'users.CustomUser'

### ============================================================================================ #
### TEMPLATE SETTINGS
### ============================================================================================ #
# import utils.context_processors.features_enabled
TEMPLATES = [
      {
            'BACKEND':  'django.template.backends.django.DjangoTemplates',
            'DIRS':     [
                  'templates',
                  'static',
                  'staticfiles',
                  'media',
                  'mediafiles',
            ],
            'APP_DIRS': True,
            'OPTIONS':  {
                  'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                        
                        ### CUSTOM CONTEXT PROCESSOR
                        'utils.context_processors.custom_context.custom_context',
                  ],
            },
      },
]

WSGI_APPLICATION = 'Portolio.wsgi.application'

### ============================================================================================ #
### POSTGRESQL - DATABASE
### ============================================================================================ #
DATABASES = {
      'default': {
            'ENGINE': 'django.db.backends.sqlite3',  # SQLITE3
            'NAME':   BASE_DIR / 'db.sqlite3',
      },
}

### ============================================================================================ #
### PASSWORD VALIDATION
### ============================================================================================ #
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
      {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
      },
      {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
      },
      {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
      },
      {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
      },
]

### ============================================================================================ #
### STATIC FILES AND MEDIA FILES & CLOUDINARY STORAGE
### ============================================================================================ #
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# static
# STATIC_URL -> prefix for the urls in the templates where staticfiles are stored in Development
# MEDIA_URL  -> prefix like for STATIC_URL
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join( BASE_DIR, 'media' )

STATIC_URL = '/static/'
# STATICFILES_DIRS -> in Development django will try to search here for existing staticfiles
# Should match the above folders, accordingly
STATICFILES_DIRS = [
      os.path.join( BASE_DIR, 'static' ),
      os.path.join( BASE_DIR, 'media' ),
]
# *_ROOT -> this is where the `pyhton manage.py collectstatic` command will store the files for
#           Deployment to Production ( so this should be `staticFILES` & `mediaFILES`
STATIC_ROOT = os.path.join( BASE_DIR, 'staticfiles' )  # -->

# We need to have this entry in Development as we have {% load cloudinary %} in the html templates
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'

### ============================================================================================ #
### INTERNATIONALIZATION
### ============================================================================================ #
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
