# Generated by Django 5.1.4 on 2024-12-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_adminuserprofile_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.DeleteModel(
            name='AdminUserProfile',
        ),
    ]
