# Generated by Django 5.1.4 on 2024-12-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_featuresadmin_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresadmin',
            options={'ordering': ['created']},
        ),
    ]
