# Generated by Django 5.1.4 on 2024-12-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_featuresadmin_options'),
        ('users', '0004_userprofile_otp_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default='_default_feature.png', upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.DeleteModel(
            name='FeaturesAdmin',
        ),
    ]
